Do not fail if there is only blog post in the future
This manifest with the following traceback :
       error  build/blog/feed.xml
  undefined method `date' for nil:NilClass
  /home/fedora/atomic-site/source/feed.xml.builder:10:in `block (2 levels) in singleton class'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing

The cause is that blog.articles.first will be Nil if there is no blog
post and yet the blog exist ( since there is article to be published )